"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, Ban, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Certificate = { id: string; name: string };
type ManagedServer = { id: string; name: string };
type Deployment = { id: string; certificateId: string; certificateName: string; domain: string; trigger: string; status: string; createdAt: string; finishedAt: string | null; errorSummary: string | null };
type LogEntry = { id?: string; sequence: number; level: string; message: string; createdAt: string; certificateName?: string | null; serverName?: string | null };
type Detail = Deployment & { targets: { id: string; serverName: string; host: string; status: string; exitCode: number | null; errorSummary: string | null }[]; logs: LogEntry[] };
type AuditEntry = { id: string; action: string; objectType: string; objectId: string | null; result: string; createdAt: string };
const terminal = new Set(["succeeded", "failed", "cancelled", "partial"]);
const formatDate = (value: string) => new Intl.DateTimeFormat("zh-CN", { dateStyle: "short", timeStyle: "medium", timeZone: "Asia/Shanghai" }).format(new Date(value));

export function ActivityPanel({ certificates, servers }: { certificates: Certificate[]; servers: ManagedServer[] }) {
  const [deployments, setDeployments] = useState<Deployment[]>([]);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [auditEvents, setAuditEvents] = useState<AuditEntry[]>([]);
  const [selected, setSelected] = useState<Detail | null>(null);
  const [certificateId, setCertificateId] = useState("");
  const [serverId, setServerId] = useState("");
  const [from, setFrom] = useState("");
  const query = useMemo(() => new URLSearchParams(Object.entries({ certificateId, serverId, from: from && new Date(`${from}T00:00:00+08:00`).toISOString() }).filter(([, value]) => value)).toString(), [certificateId, serverId, from]);
  const load = async () => {
    const [deploymentResponse, logResponse, auditResponse] = await Promise.all([fetch("/api/deployments", { cache: "no-store" }), fetch(`/api/logs?${query}`, { cache: "no-store" }), fetch("/api/audit-events", { cache: "no-store" })]);
    if (!deploymentResponse.ok || !logResponse.ok || !auditResponse.ok) throw new Error("无法加载任务历史");
    setDeployments((await deploymentResponse.json()).data); setLogs((await logResponse.json()).data); setAuditEvents((await auditResponse.json()).data);
  };
  useEffect(() => { load().catch((cause) => toast.error(cause.message)); }, [query]);
  const open = async (id: string) => { const response = await fetch(`/api/deployments/${id}`, { cache: "no-store" }); if (!response.ok) return toast.error("无法加载任务详情"); setSelected((await response.json()).data); };
  useEffect(() => { if (!selected || terminal.has(selected.status)) return; const source = new EventSource(`/api/deployments/${selected.id}/events`); source.onmessage = (event) => { const entry = JSON.parse(event.data) as LogEntry; setSelected((current) => current?.id === selected.id ? { ...current, logs: [...current.logs, entry] } : current); }; source.addEventListener("end", () => { source.close(); open(selected.id); }); return () => source.close(); }, [selected?.id, selected?.status]);
  const action = async (id: string, name: "retry" | "cancel") => { const response = await fetch(`/api/deployments/${id}/${name}`, { method: "POST" }); if (!response.ok) return toast.error("操作未完成"); toast.success(name === "retry" ? "重试任务已创建" : "任务已取消"); await load().catch((cause) => toast.error(cause.message)); if (name === "cancel") await open(id); };

  return <div className="space-y-6">
    <Card><CardHeader><CardTitle>任务历史</CardTitle><CardDescription>最多显示最近 100 个任务；选择任务可查看目标状态与实时日志。</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Select value={certificateId || "all"} onValueChange={(value) => setCertificateId(value === "all" ? "" : value)}><SelectTrigger><SelectValue placeholder="按证书筛选" /></SelectTrigger><SelectContent><SelectItem value="all">所有证书</SelectItem>{certificates.map((certificate) => <SelectItem key={certificate.id} value={certificate.id}>{certificate.name}</SelectItem>)}</SelectContent></Select><Select value={serverId || "all"} onValueChange={(value) => setServerId(value === "all" ? "" : value)}><SelectTrigger><SelectValue placeholder="按服务器筛选" /></SelectTrigger><SelectContent><SelectItem value="all">所有服务器</SelectItem>{servers.map((server) => <SelectItem key={server.id} value={server.id}>{server.name}</SelectItem>)}</SelectContent></Select><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} aria-label="开始日期" /></div><Table><TableHeader><TableRow><TableHead>证书</TableHead><TableHead>触发</TableHead><TableHead>状态</TableHead><TableHead>创建时间</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{deployments.map((deployment) => <TableRow key={deployment.id}><TableCell className="font-medium">{deployment.certificateName}<p className="mt-1 text-xs font-normal text-muted-foreground">{deployment.domain}</p></TableCell><TableCell>{deployment.trigger}</TableCell><TableCell><Badge variant={deployment.status === "succeeded" ? "default" : deployment.status === "failed" ? "destructive" : "secondary"}>{deployment.status}</Badge></TableCell><TableCell className="text-xs">{formatDate(deployment.createdAt)}</TableCell><TableCell className="space-x-1 text-right"><Button variant="outline" size="sm" onClick={() => open(deployment.id)}>详情</Button>{!terminal.has(deployment.status) && <Button variant="outline" size="icon" onClick={() => action(deployment.id, "cancel")} aria-label="取消任务"><Ban className="size-4" /></Button>}{terminal.has(deployment.status) && deployment.status !== "succeeded" && <Button variant="outline" size="icon" onClick={() => action(deployment.id, "retry")} aria-label="重试任务"><RotateCcw className="size-4" /></Button>}</TableCell></TableRow>)}{deployments.length === 0 && <TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">暂无任务</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
    {selected && <Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>任务详情</CardTitle><CardDescription>{selected.id}</CardDescription></div><Button variant="ghost" onClick={() => setSelected(null)}>关闭</Button></CardHeader><CardContent className="grid gap-6 lg:grid-cols-2"><div><h3 className="mb-2 text-sm font-medium">目标状态</h3>{selected.targets.map((target) => <div key={target.id} className="mb-2 rounded-md border p-3 text-sm"><div className="flex justify-between gap-3"><span>{target.serverName} <span className="text-muted-foreground">{target.host}</span></span><Badge variant={target.status === "succeeded" ? "default" : target.status === "failed" ? "destructive" : "secondary"}>{target.status}</Badge></div>{target.errorSummary && <p className="mt-2 text-xs text-destructive">{target.errorSummary}</p>}</div>)}</div><div><h3 className="mb-2 flex items-center gap-2 text-sm font-medium"><Activity className="size-4" />日志</h3><div className="max-h-80 space-y-2 overflow-auto rounded-md bg-slate-950 p-3 font-mono text-xs text-slate-100">{selected.logs.map((entry) => <p key={`${entry.sequence}-${entry.createdAt}`}><span className="text-slate-500">{formatDate(entry.createdAt)} </span><span className={entry.level === "error" ? "text-red-300" : "text-emerald-300"}>{entry.level.toUpperCase()}</span> {entry.message}</p>)}{selected.logs.length === 0 && <p className="text-slate-400">等待任务日志…</p>}</div></div></CardContent></Card>}
    <Card><CardHeader><CardTitle>历史日志</CardTitle><CardDescription>支持按证书、服务器与开始日期筛选，最多返回 200 条。</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>时间</TableHead><TableHead>对象</TableHead><TableHead>级别</TableHead><TableHead>消息</TableHead></TableRow></TableHeader><TableBody>{logs.map((entry) => <TableRow key={entry.id}><TableCell className="whitespace-nowrap text-xs">{formatDate(entry.createdAt)}</TableCell><TableCell className="text-xs">{entry.certificateName ?? "—"}{entry.serverName && ` / ${entry.serverName}`}</TableCell><TableCell><Badge variant={entry.level === "error" ? "destructive" : "secondary"}>{entry.level}</Badge></TableCell><TableCell>{entry.message}</TableCell></TableRow>)}{logs.length === 0 && <TableRow><TableCell colSpan={4} className="h-20 text-center text-muted-foreground">暂无匹配日志</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
    <Card><CardHeader><CardTitle>审计记录</CardTitle><CardDescription>记录管理员对证书、服务器和部署策略的变更。</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>时间</TableHead><TableHead>操作</TableHead><TableHead>对象</TableHead><TableHead>结果</TableHead></TableRow></TableHeader><TableBody>{auditEvents.map((entry) => <TableRow key={entry.id}><TableCell className="text-xs">{formatDate(entry.createdAt)}</TableCell><TableCell>{entry.action}</TableCell><TableCell className="text-xs">{entry.objectType} / {entry.objectId ?? "—"}</TableCell><TableCell><Badge variant={entry.result === "success" ? "default" : "destructive"}>{entry.result}</Badge></TableCell></TableRow>)}{auditEvents.length === 0 && <TableRow><TableCell colSpan={4} className="h-20 text-center text-muted-foreground">暂无审计记录</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
  </div>;
}
